### ISSUE TITLE
Error noticed in console log.

### ISSUE THREAD

**Issue by codemonkeyneo** [stherrienaspnet/D3-Radial-Gauge#2]
Great control , I wanted to try and use this and have multiple controls on the same page. I noticed that I I'm having issues due to there being a JavaScript error ;

Error: Invalid value for <text> attribute x="NaN" 

This stops me from being able to target a set of items with the same class (I may change code to workaround this).

Any chance of anyone looking into fixing this.

Cheers

**Comment by stherrienaspnet** [comment]
Hello could you provide me a jsfiddle link so I could assist you.

**Comment by jorgesanchez33** [comment]
Hi, I can see the error message in console too. You can see here: http://jsfiddle.net/b9674uho/1/

**Comment by stherrienaspnet** [comment]
I Just fixed the issue on github, download the latest version.

On Wed, Sep 10, 2014 at 8:57 PM, codemonkeyneo notifications@github.com
wrote:

> Great control , I wanted to try and use this and have multiple controls on
> the same page. I noticed that I I'm having issues due to there being a
> JavaScript error ;
> 
> Error: Invalid value for attribute x="NaN"
> 
> This stops me from being able to target a set of items with the same class
> (I may change code to workaround this).
> 
> Any chance of anyone looking into fixing this.
> 
> Cheers
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stherrienaspnet/D3-Radial-Gauge/issues/2.

##

**Comment by stherrienaspnet** [comment]
I Just fixed the issue on github, download the latest version.

On Wed, Sep 24, 2014 at 10:05 AM, jorgesanchez33 notifications@github.com
wrote:

> Hi, I can see the error message in console too. You can see here:
> http://jsfiddle.net/b9674uho/1/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stherrienaspnet/D3-Radial-Gauge/issues/2#issuecomment-56674283
> .

##
